#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDayTelerik.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OpenDay")]
	public partial class ODdataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertREGIST(REGIST instance);
    partial void UpdateREGIST(REGIST instance);
    partial void DeleteREGIST(REGIST instance);
    partial void InsertCHECKIN(CHECKIN instance);
    partial void UpdateCHECKIN(CHECKIN instance);
    partial void DeleteCHECKIN(CHECKIN instance);
    partial void InsertUSER(USER instance);
    partial void UpdateUSER(USER instance);
    partial void DeleteUSER(USER instance);
    #endregion
		
		public ODdataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OpenDayConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ODdataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ODdataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ODdataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ODdataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CLASS> CLASSes
		{
			get
			{
				return this.GetTable<CLASS>();
			}
		}
		
		public System.Data.Linq.Table<REGIST> REGISTs
		{
			get
			{
				return this.GetTable<REGIST>();
			}
		}
		
		public System.Data.Linq.Table<_CLASS> _CLASSes
		{
			get
			{
				return this.GetTable<_CLASS>();
			}
		}
		
		public System.Data.Linq.Table<View_Regist_Full> View_Regist_Fulls
		{
			get
			{
				return this.GetTable<View_Regist_Full>();
			}
		}
		
		public System.Data.Linq.Table<CHECKIN> CHECKINs
		{
			get
			{
				return this.GetTable<CHECKIN>();
			}
		}
		
		public System.Data.Linq.Table<View_Pivot_Class> View_Pivot_Classes
		{
			get
			{
				return this.GetTable<View_Pivot_Class>();
			}
		}
		
		public System.Data.Linq.Table<View_Checkin_Full> View_Checkin_Fulls
		{
			get
			{
				return this.GetTable<View_Checkin_Full>();
			}
		}
		
		public System.Data.Linq.Table<USER> USERs
		{
			get
			{
				return this.GetTable<USER>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_AddRegist")]
		public int sp_AddRegist([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLASS_ID", DbType="Int")] System.Nullable<int> cLASS_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="NChar(10)")] string uSER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TYPE", DbType="NChar(50)")] string tYPE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIMESTART", DbType="NChar(30)")] string tIMESTART, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GROUPCLASS", DbType="Int")] System.Nullable<int> gROUPCLASS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cLASS_ID, uSER_ID, tYPE, tIMESTART, gROUPCLASS);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_AddUser")]
		public int sp_AddUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="NChar(10)")] string iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FULLNAME", DbType="NVarChar(300)")] string fULLNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMAIL", DbType="NVarChar(50)")] string eMAIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PHONE", DbType="NVarChar(20)")] string pHONE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="STUDENT", DbType="Bit")] System.Nullable<bool> sTUDENT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SCHOOL", DbType="NVarChar(150)")] string sCHOOL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLASS", DbType="NVarChar(10)")] string cLASS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CITY", DbType="NVarChar(100)")] string cITY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, fULLNAME, eMAIL, pHONE, sTUDENT, sCHOOL, cLASS, cITY);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sl_thamdu", IsComposable=true)]
		public System.Nullable<int> sl_thamdu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sl_dangky", IsComposable=true)]
		public System.Nullable<int> sl_dangky([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLASS")]
	public partial class CLASS
	{
		
		private int _ID;
		
		private string _TIMESTART;
		
		private string _TIMEEND;
		
		private string _TYPE;
		
		private string _CLASSNAME;
		
		private System.Nullable<int> _PAX;
		
		private string _DESCRIPT;
		
		private string _ROOM;
		
		private System.Nullable<int> _COLSTART;
		
		private System.Nullable<int> _ROWSTAR;
		
		private System.Nullable<int> _ROWSPAN;
		
		private System.Nullable<int> _GROUPCLASS;
		
		public CLASS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMESTART", DbType="NChar(10)")]
		public string TIMESTART
		{
			get
			{
				return this._TIMESTART;
			}
			set
			{
				if ((this._TIMESTART != value))
				{
					this._TIMESTART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMEEND", DbType="NChar(10)")]
		public string TIMEEND
		{
			get
			{
				return this._TIMEEND;
			}
			set
			{
				if ((this._TIMEEND != value))
				{
					this._TIMEEND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(50)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASSNAME", DbType="NVarChar(200)")]
		public string CLASSNAME
		{
			get
			{
				return this._CLASSNAME;
			}
			set
			{
				if ((this._CLASSNAME != value))
				{
					this._CLASSNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAX", DbType="Int")]
		public System.Nullable<int> PAX
		{
			get
			{
				return this._PAX;
			}
			set
			{
				if ((this._PAX != value))
				{
					this._PAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPT", DbType="NVarChar(200)")]
		public string DESCRIPT
		{
			get
			{
				return this._DESCRIPT;
			}
			set
			{
				if ((this._DESCRIPT != value))
				{
					this._DESCRIPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM", DbType="NChar(10)")]
		public string ROOM
		{
			get
			{
				return this._ROOM;
			}
			set
			{
				if ((this._ROOM != value))
				{
					this._ROOM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLSTART", DbType="Int")]
		public System.Nullable<int> COLSTART
		{
			get
			{
				return this._COLSTART;
			}
			set
			{
				if ((this._COLSTART != value))
				{
					this._COLSTART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWSTAR", DbType="Int")]
		public System.Nullable<int> ROWSTAR
		{
			get
			{
				return this._ROWSTAR;
			}
			set
			{
				if ((this._ROWSTAR != value))
				{
					this._ROWSTAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWSPAN", DbType="Int")]
		public System.Nullable<int> ROWSPAN
		{
			get
			{
				return this._ROWSPAN;
			}
			set
			{
				if ((this._ROWSPAN != value))
				{
					this._ROWSPAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPCLASS", DbType="Int")]
		public System.Nullable<int> GROUPCLASS
		{
			get
			{
				return this._GROUPCLASS;
			}
			set
			{
				if ((this._GROUPCLASS != value))
				{
					this._GROUPCLASS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.REGIST")]
	public partial class REGIST : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _USER_ID;
		
		private System.Nullable<int> _CLASS_ID;
		
		private System.Nullable<System.DateTime> _TIME;
		
		private string _TYPE;
		
		private string _TIMESTART;
		
		private System.Nullable<int> _GROUPCLASS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUSER_IDChanging(string value);
    partial void OnUSER_IDChanged();
    partial void OnCLASS_IDChanging(System.Nullable<int> value);
    partial void OnCLASS_IDChanged();
    partial void OnTIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnTIMEChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnTIMESTARTChanging(string value);
    partial void OnTIMESTARTChanged();
    partial void OnGROUPCLASSChanging(System.Nullable<int> value);
    partial void OnGROUPCLASSChanged();
    #endregion
		
		public REGIST()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="NChar(10)")]
		public string USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this.OnUSER_IDChanging(value);
					this.SendPropertyChanging();
					this._USER_ID = value;
					this.SendPropertyChanged("USER_ID");
					this.OnUSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_ID", DbType="Int")]
		public System.Nullable<int> CLASS_ID
		{
			get
			{
				return this._CLASS_ID;
			}
			set
			{
				if ((this._CLASS_ID != value))
				{
					this.OnCLASS_IDChanging(value);
					this.SendPropertyChanging();
					this._CLASS_ID = value;
					this.SendPropertyChanged("CLASS_ID");
					this.OnCLASS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> TIME
		{
			get
			{
				return this._TIME;
			}
			set
			{
				if ((this._TIME != value))
				{
					this.OnTIMEChanging(value);
					this.SendPropertyChanging();
					this._TIME = value;
					this.SendPropertyChanged("TIME");
					this.OnTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NChar(30)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMESTART", DbType="NChar(10)")]
		public string TIMESTART
		{
			get
			{
				return this._TIMESTART;
			}
			set
			{
				if ((this._TIMESTART != value))
				{
					this.OnTIMESTARTChanging(value);
					this.SendPropertyChanging();
					this._TIMESTART = value;
					this.SendPropertyChanged("TIMESTART");
					this.OnTIMESTARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPCLASS", DbType="Int")]
		public System.Nullable<int> GROUPCLASS
		{
			get
			{
				return this._GROUPCLASS;
			}
			set
			{
				if ((this._GROUPCLASS != value))
				{
					this.OnGROUPCLASSChanging(value);
					this.SendPropertyChanging();
					this._GROUPCLASS = value;
					this.SendPropertyChanged("GROUPCLASS");
					this.OnGROUPCLASSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_CLASS]")]
	public partial class _CLASS
	{
		
		private System.Nullable<int> _ID;
		
		private string _TIMESTART;
		
		private string _TIMEEND;
		
		private string _CLASSNAME;
		
		private string _ROOM;
		
		private System.Nullable<int> _PAX;
		
		private System.Nullable<int> _TYPE;
		
		private string _INFO;
		
		private System.Nullable<int> _GROUPCLASS;
		
		public _CLASS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMESTART", DbType="NChar(10)")]
		public string TIMESTART
		{
			get
			{
				return this._TIMESTART;
			}
			set
			{
				if ((this._TIMESTART != value))
				{
					this._TIMESTART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMEEND", DbType="NChar(10)")]
		public string TIMEEND
		{
			get
			{
				return this._TIMEEND;
			}
			set
			{
				if ((this._TIMEEND != value))
				{
					this._TIMEEND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASSNAME", DbType="NVarChar(200)")]
		public string CLASSNAME
		{
			get
			{
				return this._CLASSNAME;
			}
			set
			{
				if ((this._CLASSNAME != value))
				{
					this._CLASSNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM", DbType="NChar(20)")]
		public string ROOM
		{
			get
			{
				return this._ROOM;
			}
			set
			{
				if ((this._ROOM != value))
				{
					this._ROOM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAX", DbType="Int")]
		public System.Nullable<int> PAX
		{
			get
			{
				return this._PAX;
			}
			set
			{
				if ((this._PAX != value))
				{
					this._PAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="Int")]
		public System.Nullable<int> TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INFO", DbType="NVarChar(200)")]
		public string INFO
		{
			get
			{
				return this._INFO;
			}
			set
			{
				if ((this._INFO != value))
				{
					this._INFO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPCLASS", DbType="Int")]
		public System.Nullable<int> GROUPCLASS
		{
			get
			{
				return this._GROUPCLASS;
			}
			set
			{
				if ((this._GROUPCLASS != value))
				{
					this._GROUPCLASS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Regist_Full")]
	public partial class View_Regist_Full
	{
		
		private string _USER_ID;
		
		private System.Nullable<int> _CLASS_ID;
		
		private string _FULLNAME;
		
		private string _TIMESTART;
		
		private System.Nullable<int> _GROUPCLASS;
		
		private string _TIMEEND;
		
		private string _CLASSNAME;
		
		private string _ROOM;
		
		private System.Nullable<int> _TYPE;
		
		private System.Nullable<int> _PAX;
		
		private string _EMAIL;
		
		private string _PHONE;
		
		private string _STUDENT;
		
		private string _SCHOOL;
		
		private string _CLASS;
		
		private string _CITY;
		
		public View_Regist_Full()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="NChar(10)")]
		public string USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this._USER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_ID", DbType="Int")]
		public System.Nullable<int> CLASS_ID
		{
			get
			{
				return this._CLASS_ID;
			}
			set
			{
				if ((this._CLASS_ID != value))
				{
					this._CLASS_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME", DbType="NVarChar(300)")]
		public string FULLNAME
		{
			get
			{
				return this._FULLNAME;
			}
			set
			{
				if ((this._FULLNAME != value))
				{
					this._FULLNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMESTART", DbType="NChar(10)")]
		public string TIMESTART
		{
			get
			{
				return this._TIMESTART;
			}
			set
			{
				if ((this._TIMESTART != value))
				{
					this._TIMESTART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPCLASS", DbType="Int")]
		public System.Nullable<int> GROUPCLASS
		{
			get
			{
				return this._GROUPCLASS;
			}
			set
			{
				if ((this._GROUPCLASS != value))
				{
					this._GROUPCLASS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMEEND", DbType="NChar(10)")]
		public string TIMEEND
		{
			get
			{
				return this._TIMEEND;
			}
			set
			{
				if ((this._TIMEEND != value))
				{
					this._TIMEEND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASSNAME", DbType="NVarChar(200)")]
		public string CLASSNAME
		{
			get
			{
				return this._CLASSNAME;
			}
			set
			{
				if ((this._CLASSNAME != value))
				{
					this._CLASSNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM", DbType="NChar(20)")]
		public string ROOM
		{
			get
			{
				return this._ROOM;
			}
			set
			{
				if ((this._ROOM != value))
				{
					this._ROOM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="Int")]
		public System.Nullable<int> TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAX", DbType="Int")]
		public System.Nullable<int> PAX
		{
			get
			{
				return this._PAX;
			}
			set
			{
				if ((this._PAX != value))
				{
					this._PAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE", DbType="NChar(20)")]
		public string PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this._PHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDENT", DbType="NVarChar(100)")]
		public string STUDENT
		{
			get
			{
				return this._STUDENT;
			}
			set
			{
				if ((this._STUDENT != value))
				{
					this._STUDENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHOOL", DbType="NVarChar(150)")]
		public string SCHOOL
		{
			get
			{
				return this._SCHOOL;
			}
			set
			{
				if ((this._SCHOOL != value))
				{
					this._SCHOOL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS", DbType="NVarChar(100)")]
		public string CLASS
		{
			get
			{
				return this._CLASS;
			}
			set
			{
				if ((this._CLASS != value))
				{
					this._CLASS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="NVarChar(100)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this._CITY = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHECKIN")]
	public partial class CHECKIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _USER_ID;
		
		private string _CLASS_ID;
		
		private System.Nullable<System.DateTime> _TIME;
		
		private string _USER_CHECK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUSER_IDChanging(string value);
    partial void OnUSER_IDChanged();
    partial void OnCLASS_IDChanging(string value);
    partial void OnCLASS_IDChanged();
    partial void OnTIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnTIMEChanged();
    partial void OnUSER_CHECKChanging(string value);
    partial void OnUSER_CHECKChanged();
    #endregion
		
		public CHECKIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="NChar(10)")]
		public string USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this.OnUSER_IDChanging(value);
					this.SendPropertyChanging();
					this._USER_ID = value;
					this.SendPropertyChanged("USER_ID");
					this.OnUSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_ID", DbType="NChar(10)")]
		public string CLASS_ID
		{
			get
			{
				return this._CLASS_ID;
			}
			set
			{
				if ((this._CLASS_ID != value))
				{
					this.OnCLASS_IDChanging(value);
					this.SendPropertyChanging();
					this._CLASS_ID = value;
					this.SendPropertyChanged("CLASS_ID");
					this.OnCLASS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> TIME
		{
			get
			{
				return this._TIME;
			}
			set
			{
				if ((this._TIME != value))
				{
					this.OnTIMEChanging(value);
					this.SendPropertyChanging();
					this._TIME = value;
					this.SendPropertyChanged("TIME");
					this.OnTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_CHECK", DbType="NChar(10)")]
		public string USER_CHECK
		{
			get
			{
				return this._USER_CHECK;
			}
			set
			{
				if ((this._USER_CHECK != value))
				{
					this.OnUSER_CHECKChanging(value);
					this.SendPropertyChanging();
					this._USER_CHECK = value;
					this.SendPropertyChanged("USER_CHECK");
					this.OnUSER_CHECKChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Pivot_Class")]
	public partial class View_Pivot_Class
	{
		
		private System.Nullable<int> _ID;
		
		private string _CLASSNAME;
		
		private System.Nullable<int> _GROUPCLASS;
		
		private string _TIMESTART;
		
		private string _TIMEEND;
		
		private System.Nullable<int> _TYPE;
		
		private string _ROOM;
		
		private System.Nullable<int> _PAX;
		
		private System.Nullable<int> _PAXREG;
		
		private System.Nullable<int> _PAXCHECKIN;
		
		public View_Pivot_Class()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASSNAME", DbType="NVarChar(200)")]
		public string CLASSNAME
		{
			get
			{
				return this._CLASSNAME;
			}
			set
			{
				if ((this._CLASSNAME != value))
				{
					this._CLASSNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPCLASS", DbType="Int")]
		public System.Nullable<int> GROUPCLASS
		{
			get
			{
				return this._GROUPCLASS;
			}
			set
			{
				if ((this._GROUPCLASS != value))
				{
					this._GROUPCLASS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMESTART", DbType="NChar(10)")]
		public string TIMESTART
		{
			get
			{
				return this._TIMESTART;
			}
			set
			{
				if ((this._TIMESTART != value))
				{
					this._TIMESTART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMEEND", DbType="NChar(10)")]
		public string TIMEEND
		{
			get
			{
				return this._TIMEEND;
			}
			set
			{
				if ((this._TIMEEND != value))
				{
					this._TIMEEND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="Int")]
		public System.Nullable<int> TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM", DbType="NChar(20)")]
		public string ROOM
		{
			get
			{
				return this._ROOM;
			}
			set
			{
				if ((this._ROOM != value))
				{
					this._ROOM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAX", DbType="Int")]
		public System.Nullable<int> PAX
		{
			get
			{
				return this._PAX;
			}
			set
			{
				if ((this._PAX != value))
				{
					this._PAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAXREG", DbType="Int")]
		public System.Nullable<int> PAXREG
		{
			get
			{
				return this._PAXREG;
			}
			set
			{
				if ((this._PAXREG != value))
				{
					this._PAXREG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAXCHECKIN", DbType="Int")]
		public System.Nullable<int> PAXCHECKIN
		{
			get
			{
				return this._PAXCHECKIN;
			}
			set
			{
				if ((this._PAXCHECKIN != value))
				{
					this._PAXCHECKIN = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Checkin_Full")]
	public partial class View_Checkin_Full
	{
		
		private string _CLASS_ID;
		
		private string _ID;
		
		private string _FULLNAME;
		
		private string _EMAIL;
		
		private string _PHONE;
		
		private string _STUDENT;
		
		private string _SCHOOL;
		
		private string _CLASS;
		
		private string _CITY;
		
		private string _CLASSNAME;
		
		private System.Nullable<int> _TYPE;
		
		private string _TIMESTART;
		
		private string _TIMEEND;
		
		private System.Nullable<int> _GROUPCLASS;
		
		private System.Nullable<int> _PAX;
		
		private int _checkinID;
		
		public View_Checkin_Full()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS_ID", DbType="NChar(10)")]
		public string CLASS_ID
		{
			get
			{
				return this._CLASS_ID;
			}
			set
			{
				if ((this._CLASS_ID != value))
				{
					this._CLASS_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME", DbType="NVarChar(300)")]
		public string FULLNAME
		{
			get
			{
				return this._FULLNAME;
			}
			set
			{
				if ((this._FULLNAME != value))
				{
					this._FULLNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE", DbType="NChar(20)")]
		public string PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this._PHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDENT", DbType="NVarChar(100)")]
		public string STUDENT
		{
			get
			{
				return this._STUDENT;
			}
			set
			{
				if ((this._STUDENT != value))
				{
					this._STUDENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHOOL", DbType="NVarChar(150)")]
		public string SCHOOL
		{
			get
			{
				return this._SCHOOL;
			}
			set
			{
				if ((this._SCHOOL != value))
				{
					this._SCHOOL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS", DbType="NVarChar(100)")]
		public string CLASS
		{
			get
			{
				return this._CLASS;
			}
			set
			{
				if ((this._CLASS != value))
				{
					this._CLASS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="NVarChar(100)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this._CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASSNAME", DbType="NVarChar(200)")]
		public string CLASSNAME
		{
			get
			{
				return this._CLASSNAME;
			}
			set
			{
				if ((this._CLASSNAME != value))
				{
					this._CLASSNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="Int")]
		public System.Nullable<int> TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMESTART", DbType="NChar(10)")]
		public string TIMESTART
		{
			get
			{
				return this._TIMESTART;
			}
			set
			{
				if ((this._TIMESTART != value))
				{
					this._TIMESTART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMEEND", DbType="NChar(10)")]
		public string TIMEEND
		{
			get
			{
				return this._TIMEEND;
			}
			set
			{
				if ((this._TIMEEND != value))
				{
					this._TIMEEND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPCLASS", DbType="Int")]
		public System.Nullable<int> GROUPCLASS
		{
			get
			{
				return this._GROUPCLASS;
			}
			set
			{
				if ((this._GROUPCLASS != value))
				{
					this._GROUPCLASS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAX", DbType="Int")]
		public System.Nullable<int> PAX
		{
			get
			{
				return this._PAX;
			}
			set
			{
				if ((this._PAX != value))
				{
					this._PAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkinID", DbType="Int NOT NULL")]
		public int checkinID
		{
			get
			{
				return this._checkinID;
			}
			set
			{
				if ((this._checkinID != value))
				{
					this._checkinID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[USER]")]
	public partial class USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _FULLNAME;
		
		private string _EMAIL;
		
		private string _PHONE;
		
		private string _STUDENT;
		
		private string _SCHOOL;
		
		private string _CLASS;
		
		private string _CITY;
		
		private int _NO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnFULLNAMEChanging(string value);
    partial void OnFULLNAMEChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnPHONEChanging(string value);
    partial void OnPHONEChanged();
    partial void OnSTUDENTChanging(string value);
    partial void OnSTUDENTChanged();
    partial void OnSCHOOLChanging(string value);
    partial void OnSCHOOLChanged();
    partial void OnCLASSChanging(string value);
    partial void OnCLASSChanged();
    partial void OnCITYChanging(string value);
    partial void OnCITYChanged();
    partial void OnNOChanging(int value);
    partial void OnNOChanged();
    #endregion
		
		public USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME", DbType="NVarChar(300)")]
		public string FULLNAME
		{
			get
			{
				return this._FULLNAME;
			}
			set
			{
				if ((this._FULLNAME != value))
				{
					this.OnFULLNAMEChanging(value);
					this.SendPropertyChanging();
					this._FULLNAME = value;
					this.SendPropertyChanged("FULLNAME");
					this.OnFULLNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE", DbType="NChar(20)")]
		public string PHONE
		{
			get
			{
				return this._PHONE;
			}
			set
			{
				if ((this._PHONE != value))
				{
					this.OnPHONEChanging(value);
					this.SendPropertyChanging();
					this._PHONE = value;
					this.SendPropertyChanged("PHONE");
					this.OnPHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDENT", DbType="NVarChar(100)")]
		public string STUDENT
		{
			get
			{
				return this._STUDENT;
			}
			set
			{
				if ((this._STUDENT != value))
				{
					this.OnSTUDENTChanging(value);
					this.SendPropertyChanging();
					this._STUDENT = value;
					this.SendPropertyChanged("STUDENT");
					this.OnSTUDENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHOOL", DbType="NVarChar(150)")]
		public string SCHOOL
		{
			get
			{
				return this._SCHOOL;
			}
			set
			{
				if ((this._SCHOOL != value))
				{
					this.OnSCHOOLChanging(value);
					this.SendPropertyChanging();
					this._SCHOOL = value;
					this.SendPropertyChanged("SCHOOL");
					this.OnSCHOOLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASS", DbType="NVarChar(100)")]
		public string CLASS
		{
			get
			{
				return this._CLASS;
			}
			set
			{
				if ((this._CLASS != value))
				{
					this.OnCLASSChanging(value);
					this.SendPropertyChanging();
					this._CLASS = value;
					this.SendPropertyChanged("CLASS");
					this.OnCLASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="NVarChar(100)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this.OnCITYChanging(value);
					this.SendPropertyChanging();
					this._CITY = value;
					this.SendPropertyChanged("CITY");
					this.OnCITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int NO
		{
			get
			{
				return this._NO;
			}
			set
			{
				if ((this._NO != value))
				{
					this.OnNOChanging(value);
					this.SendPropertyChanging();
					this._NO = value;
					this.SendPropertyChanged("NO");
					this.OnNOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
